# Generated by Django 5.2.7 on 2025-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
